//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huoyaoyuan.AdmiralRoom.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huoyaoyuan.AdmiralRoom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to game 的本地化字符串。
        /// </summary>
        public static string BackToGame {
            get {
                return ResourceManager.GetString("BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean cache 的本地化字符串。
        /// </summary>
        public static string CleanCache {
            get {
                return ResourceManager.GetString("CleanCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto 的本地化字符串。
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equips:  的本地化字符串。
        /// </summary>
        public static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification 的本地化字符串。
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefer toast notify 的本地化字符串。
        /// </summary>
        public static string Notification_Toast {
            get {
                return ResourceManager.GetString("Notification_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 10 forces to use toast notifications. To enable the BallonTip, edit registry. 的本地化字符串。
        /// </summary>
        public static string Notification_ToolTip_Win10 {
            get {
                return ResourceManager.GetString("Notification_ToolTip_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Proxy_Address {
            get {
                return ResourceManager.GetString("Proxy_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Proxy_Port {
            get {
                return ResourceManager.GetString("Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use another proxy for HTTPS 的本地化字符串。
        /// </summary>
        public static string Proxy_UseHTTPS {
            get {
                return ResourceManager.GetString("Proxy_UseHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use proxy 的本地化字符串。
        /// </summary>
        public static string Proxy_UseProxy {
            get {
                return ResourceManager.GetString("Proxy_UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string RibbonTab_Browse {
            get {
                return ResourceManager.GetString("RibbonTab_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string RibbonTab_View {
            get {
                return ResourceManager.GetString("RibbonTab_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string RibbonTab_Window {
            get {
                return ResourceManager.GetString("RibbonTab_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot 的本地化字符串。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ships:  的本地化字符串。
        /// </summary>
        public static string ShipCount {
            get {
                return ResourceManager.GetString("ShipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use aero style controls 的本地化字符串。
        /// </summary>
        public static string Theme_Aero {
            get {
                return ResourceManager.GetString("Theme_Aero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t use DWM 的本地化字符串。
        /// </summary>
        public static string Theme_NoDWM {
            get {
                return ResourceManager.GetString("Theme_NoDWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admiral 的本地化字符串。
        /// </summary>
        public static string ViewTitle_AdmiralView {
            get {
                return ResourceManager.GetString("ViewTitle_AdmiralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battle 的本地化字符串。
        /// </summary>
        public static string ViewTitle_BattleView {
            get {
                return ResourceManager.GetString("ViewTitle_BattleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building 的本地化字符串。
        /// </summary>
        public static string ViewTitle_BuildingView {
            get {
                return ResourceManager.GetString("ViewTitle_BuildingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compass 的本地化字符串。
        /// </summary>
        public static string ViewTitle_CompassView {
            get {
                return ResourceManager.GetString("ViewTitle_CompassView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development 的本地化字符串。
        /// </summary>
        public static string ViewTitle_DevelopView {
            get {
                return ResourceManager.GetString("ViewTitle_DevelopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Equipments 的本地化字符串。
        /// </summary>
        public static string ViewTitle_EquipmentCatalog {
            get {
                return ResourceManager.GetString("ViewTitle_EquipmentCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fleet 的本地化字符串。
        /// </summary>
        public static string ViewTitle_FleetView {
            get {
                return ResourceManager.GetString("ViewTitle_FleetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map HP 的本地化字符串。
        /// </summary>
        public static string ViewTitle_MapHPView {
            get {
                return ResourceManager.GetString("ViewTitle_MapHPView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expedition 的本地化字符串。
        /// </summary>
        public static string ViewTitle_MissionView {
            get {
                return ResourceManager.GetString("ViewTitle_MissionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quest In Progress 的本地化字符串。
        /// </summary>
        public static string ViewTitle_QuestOverview {
            get {
                return ResourceManager.GetString("ViewTitle_QuestOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairing 的本地化字符串。
        /// </summary>
        public static string ViewTitle_RepairView {
            get {
                return ResourceManager.GetString("ViewTitle_RepairView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Ships 的本地化字符串。
        /// </summary>
        public static string ViewTitle_ShipCatalog {
            get {
                return ResourceManager.GetString("ViewTitle_ShipCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone window 的本地化字符串。
        /// </summary>
        public static string Window_Standalone {
            get {
                return ResourceManager.GetString("Window_Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subwindow 的本地化字符串。
        /// </summary>
        public static string Window_Subwindow {
            get {
                return ResourceManager.GetString("Window_Subwindow", resourceCulture);
            }
        }
    }
}
