//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huoyaoyuan.AdmiralRoom.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huoyaoyuan.AdmiralRoom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to game 的本地化字符串。
        /// </summary>
        public static string BackToGame {
            get {
                return ResourceManager.GetString("BackToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anonymous Damage: 的本地化字符串。
        /// </summary>
        public static string Battle_AnonymousDamage {
            get {
                return ResourceManager.GetString("Battle_AnonymousDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop:  的本地化字符串。
        /// </summary>
        public static string Battle_Drop {
            get {
                return ResourceManager.GetString("Battle_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Victory A 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_A {
            get {
                return ResourceManager.GetString("Battle_WinRank_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tactical Victory B 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_B {
            get {
                return ResourceManager.GetString("Battle_WinRank_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tactical Defeat C 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_C {
            get {
                return ResourceManager.GetString("Battle_WinRank_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defeat D 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_D {
            get {
                return ResourceManager.GetString("Battle_WinRank_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Defeat E 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_E {
            get {
                return ResourceManager.GetString("Battle_WinRank_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perfect S 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_Perfect {
            get {
                return ResourceManager.GetString("Battle_WinRank_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Victory S 的本地化字符串。
        /// </summary>
        public static string Battle_WinRank_S {
            get {
                return ResourceManager.GetString("Battle_WinRank_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clean cache 的本地化字符串。
        /// </summary>
        public static string CleanCache {
            get {
                return ResourceManager.GetString("CleanCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete internet cache files? 的本地化字符串。
        /// </summary>
        public static string CleanCache_Alert {
            get {
                return ResourceManager.GetString("CleanCache_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internet cache files delete failed. 的本地化字符串。
        /// </summary>
        public static string CleanCache_Fail {
            get {
                return ResourceManager.GetString("CleanCache_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internet cache files have been deleted. 的本地化字符串。
        /// </summary>
        public static string CleanCache_Success {
            get {
                return ResourceManager.GetString("CleanCache_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aerial Battle 的本地化字符串。
        /// </summary>
        public static string Compass_AirBattle {
            get {
                return ResourceManager.GetString("Compass_AirBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aerial Search 的本地化字符串。
        /// </summary>
        public static string Compass_AirSearch {
            get {
                return ResourceManager.GetString("Compass_AirSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battle 的本地化字符串。
        /// </summary>
        public static string Compass_Battle {
            get {
                return ResourceManager.GetString("Compass_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOSS 的本地化字符串。
        /// </summary>
        public static string Compass_BOSS {
            get {
                return ResourceManager.GetString("Compass_BOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport Finish 的本地化字符串。
        /// </summary>
        public static string Compass_Guard {
            get {
                return ResourceManager.GetString("Compass_Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imagination 的本地化字符串。
        /// </summary>
        public static string Compass_Imagination {
            get {
                return ResourceManager.GetString("Compass_Imagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Get 的本地化字符串。
        /// </summary>
        public static string Compass_ItemGet {
            get {
                return ResourceManager.GetString("Compass_ItemGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Lost 的本地化字符串。
        /// </summary>
        public static string Compass_ItemLost {
            get {
                return ResourceManager.GetString("Compass_ItemLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Night Battle 的本地化字符串。
        /// </summary>
        public static string Compass_NightBattle {
            get {
                return ResourceManager.GetString("Compass_NightBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position:  的本地化字符串。
        /// </summary>
        public static string Compass_Position {
            get {
                return ResourceManager.GetString("Compass_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Route 的本地化字符串。
        /// </summary>
        public static string Compass_SelectRoute {
            get {
                return ResourceManager.GetString("Compass_SelectRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sortie Area:  的本地化字符串。
        /// </summary>
        public static string Compass_SortieArea {
            get {
                return ResourceManager.GetString("Compass_SortieArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landing Point 的本地化字符串。
        /// </summary>
        public static string Compass_Transport {
            get {
                return ResourceManager.GetString("Compass_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string Dock_Complete {
            get {
                return ResourceManager.GetString("Dock_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        public static string Dock_Empty {
            get {
                return ResourceManager.GetString("Dock_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked 的本地化字符串。
        /// </summary>
        public static string Dock_Locked {
            get {
                return ResourceManager.GetString("Dock_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ship name in building 的本地化字符串。
        /// </summary>
        public static string Dock_ShowBuild {
            get {
                return ResourceManager.GetString("Dock_ShowBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count(Left) 的本地化字符串。
        /// </summary>
        public static string Equip_CountLeft {
            get {
                return ResourceManager.GetString("Equip_CountLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Improvement 的本地化字符串。
        /// </summary>
        public static string Equip_Improvement {
            get {
                return ResourceManager.GetString("Equip_Improvement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Equip_Name {
            get {
                return ResourceManager.GetString("Equip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipped on 的本地化字符串。
        /// </summary>
        public static string Equip_OnShip {
            get {
                return ResourceManager.GetString("Equip_OnShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expedition 的本地化字符串。
        /// </summary>
        public static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back Time 的本地化字符串。
        /// </summary>
        public static string Expedition_BackTime {
            get {
                return ResourceManager.GetString("Expedition_BackTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remain 的本地化字符串。
        /// </summary>
        public static string Expedition_Remain {
            get {
                return ResourceManager.GetString("Expedition_Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail 的本地化字符串。
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Fight Power 的本地化字符串。
        /// </summary>
        public static string Fleet_AFP {
            get {
                return ResourceManager.GetString("Fleet_AFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string Fleet_AFP_Basic {
            get {
                return ResourceManager.GetString("Fleet_AFP_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proficiency Bonus 的本地化字符串。
        /// </summary>
        public static string Fleet_AFP_Bonus {
            get {
                return ResourceManager.GetString("Fleet_AFP_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fighters Only 的本地化字符串。
        /// </summary>
        public static string Fleet_AFP_Fighter {
            get {
                return ResourceManager.GetString("Fleet_AFP_Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charge Cost 的本地化字符串。
        /// </summary>
        public static string Fleet_ChargeCost {
            get {
                return ResourceManager.GetString("Fleet_ChargeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition Recovery 的本地化字符串。
        /// </summary>
        public static string Fleet_Condition {
            get {
                return ResourceManager.GetString("Fleet_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Homeport Repair 的本地化字符串。
        /// </summary>
        public static string Fleet_HomeportRepair {
            get {
                return ResourceManager.GetString("Fleet_HomeportRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Level 的本地化字符串。
        /// </summary>
        public static string Fleet_Level_Average {
            get {
                return ResourceManager.GetString("Fleet_Level_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level Sum 的本地化字符串。
        /// </summary>
        public static string Fleet_Level_Sum {
            get {
                return ResourceManager.GetString("Fleet_Level_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light of Sight 的本地化字符串。
        /// </summary>
        public static string Fleet_LoS {
            get {
                return ResourceManager.GetString("Fleet_LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair Cost 的本地化字符串。
        /// </summary>
        public static string Fleet_RepairCost {
            get {
                return ResourceManager.GetString("Fleet_RepairCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairing 的本地化字符串。
        /// </summary>
        public static string Fleet_Repairing {
            get {
                return ResourceManager.GetString("Fleet_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fleet is empty. 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_Empty {
            get {
                return ResourceManager.GetString("Fleet_Status_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship is heavily damaged. 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_HeavilyDamaged {
            get {
                return ResourceManager.GetString("Fleet_Status_HeavilyDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In expedition 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_InMission {
            get {
                return ResourceManager.GetString("Fleet_Status_InMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In sortie 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_InSortie {
            get {
                return ResourceManager.GetString("Fleet_Status_InSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition recoverying 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_LowCondition {
            get {
                return ResourceManager.GetString("Fleet_Status_LowCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charge needed. 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_NeedCharge {
            get {
                return ResourceManager.GetString("Fleet_Status_NeedCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready for sortie. 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_Ready {
            get {
                return ResourceManager.GetString("Fleet_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship is repairing 的本地化字符串。
        /// </summary>
        public static string Fleet_Status_Repairing {
            get {
                return ResourceManager.GetString("Fleet_Status_Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto 的本地化字符串。
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equips:  的本地化字符串。
        /// </summary>
        public static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute 的本地化字符串。
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification 的本地化字符串。
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Construction of {1} in Dock {0} has been completed. 的本地化字符串。
        /// </summary>
        public static string Notification_Build_Text {
            get {
                return ResourceManager.GetString("Notification_Build_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Construction Completed 的本地化字符串。
        /// </summary>
        public static string Notification_Build_Title {
            get {
                return ResourceManager.GetString("Notification_Build_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All ships in 「{0}」 have fully recovered from fatigue. 的本地化字符串。
        /// </summary>
        public static string Notification_Condition_Text {
            get {
                return ResourceManager.GetString("Notification_Condition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatigue Recovery Completed 的本地化字符串。
        /// </summary>
        public static string Notification_Condition_Title {
            get {
                return ResourceManager.GetString("Notification_Condition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 「{0}」 has returned from an expedition.
        ///Expedition {1} - {2} 的本地化字符串。
        /// </summary>
        public static string Notification_Expedition_Text {
            get {
                return ResourceManager.GetString("Notification_Expedition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expedition Completed 的本地化字符串。
        /// </summary>
        public static string Notification_Expedition_Title {
            get {
                return ResourceManager.GetString("Notification_Expedition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairs on {1} in Dock {0} have been completed. 的本地化字符串。
        /// </summary>
        public static string Notification_Repair_Text {
            get {
                return ResourceManager.GetString("Notification_Repair_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairs Completed 的本地化字符串。
        /// </summary>
        public static string Notification_Repair_Title {
            get {
                return ResourceManager.GetString("Notification_Repair_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefer toast notify 的本地化字符串。
        /// </summary>
        public static string Notification_Toast {
            get {
                return ResourceManager.GetString("Notification_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 10 forces to use toast notifications. To enable the BallonTip, edit registry. 的本地化字符串。
        /// </summary>
        public static string Notification_ToolTip_Win10 {
            get {
                return ResourceManager.GetString("Notification_ToolTip_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        public static string Predict_Disable {
            get {
                return ResourceManager.GetString("Predict_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        public static string Predict_Enable {
            get {
                return ResourceManager.GetString("Predict_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Proxy_Address {
            get {
                return ResourceManager.GetString("Proxy_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Proxy_Port {
            get {
                return ResourceManager.GetString("Proxy_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use another proxy for HTTPS 的本地化字符串。
        /// </summary>
        public static string Proxy_UseHTTPS {
            get {
                return ResourceManager.GetString("Proxy_UseHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use proxy 的本地化字符串。
        /// </summary>
        public static string Proxy_UseProxy {
            get {
                return ResourceManager.GetString("Proxy_UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Daily {
            get {
                return ResourceManager.GetString("Quest_Peroid_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date ends with 0,3,7 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Day037 {
            get {
                return ResourceManager.GetString("Quest_Peroid_Day037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date ends with 2,8 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Day28 {
            get {
                return ResourceManager.GetString("Quest_Peroid_Day28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Monthly {
            get {
                return ResourceManager.GetString("Quest_Peroid_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Once 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Once {
            get {
                return ResourceManager.GetString("Quest_Peroid_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        public static string Quest_Peroid_Weekly {
            get {
                return ResourceManager.GetString("Quest_Peroid_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair&amp;Charge 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Charge {
            get {
                return ResourceManager.GetString("Quest_Type_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exercise 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Exercise {
            get {
                return ResourceManager.GetString("Quest_Type_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expedition 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Expedition {
            get {
                return ResourceManager.GetString("Quest_Type_Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organization 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Organization {
            get {
                return ResourceManager.GetString("Quest_Type_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Other {
            get {
                return ResourceManager.GetString("Quest_Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powerup 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Powerup {
            get {
                return ResourceManager.GetString("Quest_Type_Powerup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shipyard 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Shipyard {
            get {
                return ResourceManager.GetString("Quest_Type_Shipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sortie 的本地化字符串。
        /// </summary>
        public static string Quest_Type_Sortie {
            get {
                return ResourceManager.GetString("Quest_Type_Sortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        public static string RibbonTab_Browse {
            get {
                return ResourceManager.GetString("RibbonTab_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string RibbonTab_View {
            get {
                return ResourceManager.GetString("RibbonTab_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string RibbonTab_Window {
            get {
                return ResourceManager.GetString("RibbonTab_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot 的本地化字符串。
        /// </summary>
        public static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot save failed:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Fail {
            get {
                return ResourceManager.GetString("Screenshot_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot saved:  的本地化字符串。
        /// </summary>
        public static string Screenshot_Success {
            get {
                return ResourceManager.GetString("Screenshot_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Settings_FolderOpen {
            get {
                return ResourceManager.GetString("Settings_FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Settings_FolderSelect {
            get {
                return ResourceManager.GetString("Settings_FolderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify shorting time(s):  的本地化字符串。
        /// </summary>
        public static string Settings_NotifyShortingTime {
            get {
                return ResourceManager.GetString("Settings_NotifyShortingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify when building complete 的本地化字符串。
        /// </summary>
        public static string Settings_NotifyWhenBuild {
            get {
                return ResourceManager.GetString("Settings_NotifyWhenBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify when condition recovery 的本地化字符串。
        /// </summary>
        public static string Settings_NotifyWhenCondition {
            get {
                return ResourceManager.GetString("Settings_NotifyWhenCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify when expedition complete 的本地化字符串。
        /// </summary>
        public static string Settings_NotifyWhenExpedition {
            get {
                return ResourceManager.GetString("Settings_NotifyWhenExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify when repairing complete 的本地化字符串。
        /// </summary>
        public static string Settings_NotifyWhenRepair {
            get {
                return ResourceManager.GetString("Settings_NotifyWhenRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot Folder:  的本地化字符串。
        /// </summary>
        public static string Settings_ScreenShotFolder {
            get {
                return ResourceManager.GetString("Settings_ScreenShotFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AntiAir 的本地化字符串。
        /// </summary>
        public static string Ship_AA {
            get {
                return ResourceManager.GetString("Ship_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armor 的本地化字符串。
        /// </summary>
        public static string Ship_Armor {
            get {
                return ResourceManager.GetString("Ship_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASW 的本地化字符串。
        /// </summary>
        public static string Ship_ASW {
            get {
                return ResourceManager.GetString("Ship_ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class 的本地化字符串。
        /// </summary>
        public static string Ship_Class {
            get {
                return ResourceManager.GetString("Ship_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string Ship_Cond {
            get {
                return ResourceManager.GetString("Ship_Cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipments 的本地化字符串。
        /// </summary>
        public static string Ship_Equip {
            get {
                return ResourceManager.GetString("Ship_Equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Evasion 的本地化字符串。
        /// </summary>
        public static string Ship_Evasion {
            get {
                return ResourceManager.GetString("Ship_Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        public static string Ship_Filter {
            get {
                return ResourceManager.GetString("Ship_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv. 1 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Level_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Level_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Level_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Level_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv. 2+ 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Level_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Level_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Locked 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Lock_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Lock_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Lock_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Lock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Lock_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Lock_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not In Expedition 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Mission_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Mission_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mission 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Mission_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Mission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Expedition 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Mission_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Mission_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powerup InComplete 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Powerup_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Powerup_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powerup 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Powerup_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Powerup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powerup Complete 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Powerup_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Powerup_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remodel InComplete 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Remodel_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Remodel_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remodel 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Remodel_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Remodel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remodel Complete 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Remodel_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Remodel_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Speed 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Speed_False {
            get {
                return ResourceManager.GetString("Ship_Filter_Speed_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Speed_Title {
            get {
                return ResourceManager.GetString("Ship_Filter_Speed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Speed 的本地化字符串。
        /// </summary>
        public static string Ship_Filter_Speed_True {
            get {
                return ResourceManager.GetString("Ship_Filter_Speed_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firepower 的本地化字符串。
        /// </summary>
        public static string Ship_Firepower {
            get {
                return ResourceManager.GetString("Ship_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Ship_Id {
            get {
                return ResourceManager.GetString("Ship_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Ship_Level {
            get {
                return ResourceManager.GetString("Ship_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoS 的本地化字符串。
        /// </summary>
        public static string Ship_LoS {
            get {
                return ResourceManager.GetString("Ship_LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ship 的本地化字符串。
        /// </summary>
        public static string Ship_LowerCase {
            get {
                return ResourceManager.GetString("Ship_LowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luck 的本地化字符串。
        /// </summary>
        public static string Ship_Luck {
            get {
                return ResourceManager.GetString("Ship_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Ship_Name {
            get {
                return ResourceManager.GetString("Ship_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DD 的本地化字符串。
        /// </summary>
        public static string Ship_Preset01 {
            get {
                return ResourceManager.GetString("Ship_Preset01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CL(T) 的本地化字符串。
        /// </summary>
        public static string Ship_Preset02 {
            get {
                return ResourceManager.GetString("Ship_Preset02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CA(V) 的本地化字符串。
        /// </summary>
        public static string Ship_Preset03 {
            get {
                return ResourceManager.GetString("Ship_Preset03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cruisers 的本地化字符串。
        /// </summary>
        public static string Ship_Preset04 {
            get {
                return ResourceManager.GetString("Ship_Preset04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BB(V) 的本地化字符串。
        /// </summary>
        public static string Ship_Preset05 {
            get {
                return ResourceManager.GetString("Ship_Preset05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carriers 的本地化字符串。
        /// </summary>
        public static string Ship_Preset06 {
            get {
                return ResourceManager.GetString("Ship_Preset06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CV(A) 的本地化字符串。
        /// </summary>
        public static string Ship_Preset07 {
            get {
                return ResourceManager.GetString("Ship_Preset07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SS(V) 的本地化字符串。
        /// </summary>
        public static string Ship_Preset08 {
            get {
                return ResourceManager.GetString("Ship_Preset08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seaplaners 的本地化字符串。
        /// </summary>
        public static string Ship_Preset09 {
            get {
                return ResourceManager.GetString("Ship_Preset09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specials 的本地化字符串。
        /// </summary>
        public static string Ship_Preset10 {
            get {
                return ResourceManager.GetString("Ship_Preset10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair Time 的本地化字符串。
        /// </summary>
        public static string Ship_RepairTime {
            get {
                return ResourceManager.GetString("Ship_RepairTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort 的本地化字符串。
        /// </summary>
        public static string Ship_Sort {
            get {
                return ResourceManager.GetString("Ship_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ascending 的本地化字符串。
        /// </summary>
        public static string Ship_Sort_Ascend {
            get {
                return ResourceManager.GetString("Ship_Sort_Ascend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending 的本地化字符串。
        /// </summary>
        public static string Ship_Sort_Descend {
            get {
                return ResourceManager.GetString("Ship_Sort_Descend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (None) 的本地化字符串。
        /// </summary>
        public static string Ship_Sort_None {
            get {
                return ResourceManager.GetString("Ship_Sort_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torpedo 的本地化字符串。
        /// </summary>
        public static string Ship_Torpedo {
            get {
                return ResourceManager.GetString("Ship_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ships:  的本地化字符串。
        /// </summary>
        public static string ShipCount {
            get {
                return ResourceManager.GetString("ShipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get response: {0} 的本地化字符串。
        /// </summary>
        public static string Status_GetResponse {
            get {
                return ResourceManager.GetString("Status_GetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready. 的本地化字符串。
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use aero style controls 的本地化字符串。
        /// </summary>
        public static string Theme_Aero {
            get {
                return ResourceManager.GetString("Theme_Aero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t use DWM 的本地化字符串。
        /// </summary>
        public static string Theme_NoDWM {
            get {
                return ResourceManager.GetString("Theme_NoDWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admiral 的本地化字符串。
        /// </summary>
        public static string ViewTitle_AdmiralView {
            get {
                return ResourceManager.GetString("ViewTitle_AdmiralView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battle 的本地化字符串。
        /// </summary>
        public static string ViewTitle_BattleView {
            get {
                return ResourceManager.GetString("ViewTitle_BattleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building 的本地化字符串。
        /// </summary>
        public static string ViewTitle_BuildingView {
            get {
                return ResourceManager.GetString("ViewTitle_BuildingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compass 的本地化字符串。
        /// </summary>
        public static string ViewTitle_CompassView {
            get {
                return ResourceManager.GetString("ViewTitle_CompassView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Development 的本地化字符串。
        /// </summary>
        public static string ViewTitle_DevelopView {
            get {
                return ResourceManager.GetString("ViewTitle_DevelopView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Equipments 的本地化字符串。
        /// </summary>
        public static string ViewTitle_EquipmentCatalog {
            get {
                return ResourceManager.GetString("ViewTitle_EquipmentCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fleet 的本地化字符串。
        /// </summary>
        public static string ViewTitle_FleetView {
            get {
                return ResourceManager.GetString("ViewTitle_FleetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map HP 的本地化字符串。
        /// </summary>
        public static string ViewTitle_MapHPView {
            get {
                return ResourceManager.GetString("ViewTitle_MapHPView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expedition 的本地化字符串。
        /// </summary>
        public static string ViewTitle_MissionView {
            get {
                return ResourceManager.GetString("ViewTitle_MissionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quest In Progress 的本地化字符串。
        /// </summary>
        public static string ViewTitle_QuestOverview {
            get {
                return ResourceManager.GetString("ViewTitle_QuestOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairing 的本地化字符串。
        /// </summary>
        public static string ViewTitle_RepairView {
            get {
                return ResourceManager.GetString("ViewTitle_RepairView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Ships 的本地化字符串。
        /// </summary>
        public static string ViewTitle_ShipCatalog {
            get {
                return ResourceManager.GetString("ViewTitle_ShipCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone window 的本地化字符串。
        /// </summary>
        public static string Window_Standalone {
            get {
                return ResourceManager.GetString("Window_Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subwindow 的本地化字符串。
        /// </summary>
        public static string Window_Subwindow {
            get {
                return ResourceManager.GetString("Window_Subwindow", resourceCulture);
            }
        }
    }
}
